%YAML:1.0
---
gaussian_kernel_h:
   type: 3
   value: 15
   max: 100
   id: Bulr Kernel Height
gaussian_kernel_w:
   type: 3
   value: 15
   max: 100
   id: Bulr Kernel Width
hough_min_radis:
   type: 0
   value: 9
   max: 100
   id: Minimal Circle Radius
hough_min_dist:
   type: 2
   value: 30.
   max: 150.
   id: Minimal Circle Distance
gaussian_sigma_y:
   type: 2
   value: 2.
   max: 20.
   id: Bulr Sigma Y
gaussian_sigma_x:
   type: 2
   value: 2.
   max: 20.
   id: Bulr Sigma X
hough_dp:
   type: 2
   value: 2.0000000000000001e-01
   max: 10.
   id: Hough Circle DP
hough_p1:
   type: 2
   value: 148.
   max: 500.
   id: Hough Circle Parm1
hough_p2:
   type: 2
   value: 10.
   max: 50.
   id: Hough Circle Parm2
hough_max_radis:
   type: 0
   value: 11
   max: 100
   id: Maximal Circle Radius
